
# SEO
title: My furst Theme
description: A typographic theme.

# social
social_link: 
social_username: Cyberlizard
github_repo: Cyberlizard # the GitHub repo name for your project
github_username: Cyberlizard
theme_color: black

# Theme
remote_theme: 'internet-de-france/swiss'
baseurl: '/cyberstak'

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      category_name: ""
  -
    scope:
      path: ""
      type: "posts"
    values:
      categories: ""

# Stastic UI
remote_theme_layouts: 
  - ""
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble

theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow


